In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
#| default_exp profile

# Profile

> Set of functions for calculating roughness parameters 

In [ ]:
#| hide
from nbdev.showdoc import *

In [ ]:
#| export
import numpy as np
from PIL import Image  

In [ ]:
isinstance(np.array([0.0]),np.ndarray)

True

In [ ]:
test_array = np.array([[1,2,],[4,2]])
np.mean(test_array, axis = 0)
np.subtract(test_array, np.mean(test_array, axis = 1))

array([[-0.5, -1. ],
       [ 2.5, -1. ]])

In [ ]:
test_array_2 = np.array([[1,2,3,4,5], [5,5,5,5,5]])
np.mean(test_array_2, axis = 0)

array([3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
test_array_2 - np.mean(test_array_2,axis = 0)

array([[-2. , -1.5, -1. , -0.5,  0. ],
       [ 2. ,  1.5,  1. ,  0.5,  0. ]])

In [ ]:
#| export
def Ra(im, axis = 0, norm = True):
    '''
    Calculates Mean Absolute Roughness (Ra) along given axis. Calculated as the average deviation of absolute height values from the mean line of a given profile.
    '''
    if norm:
        im = im - np.mean(im, axis = axis)
    return np.mean(np.absolute(im))

In [ ]:
Ra(test_array_2,norm = True)

1.0

In [ ]:
#| export
def Rms(im, axis = 0, norm = True):
    '''
    Calculates Root Mean Square Roughness (Rms) along given axis. Calculated as the root mean square of deviations of height from the mean line of a given profile. 
    '''
    if norm:
        im = im - np.mean(im, axis = axis)
    return np.sqrt(np.mean(np.square(im), axis = axis))

In [ ]:
show_doc(Ra)

---

#### Ra

>      Ra (im, axis=0, norm=True)

Calculates Mean Absolute Roughness (Ra) along given axis. Calculated as the average deviation of absolute height values from the mean line of a given profile.

In [ ]:
#| hide
from nbdev import nbdev_export
nbdev_export()