In [ ]:
%load_ext autoreload
%autoreload 2

In [ ]:
#| default_exp section

# Section

> Set of functions for calculating 2 Dimensional surface parameters across sections

In [ ]:
#| export
from rough.data import *
from rough.profile import *

import numpy as np
from matplotlib import pyplot as plt
from scipy.stats import skew, kurtosis
from scipy.signal import find_peaks

To demonstrate, we're going to build on data we processed in `data`

In [ ]:
image    = np.loadtxt('example.txt')
sections = np.load('example_sections.npy')

In [ ]:
#| export
def Sa(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Sa of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
      ):
    '''
    Calculates the mean absolute difference from the mean plane. Equivalent to Ra(array, axis = None)
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims=True)
        
    return np.mean(np.absolute(im), axis = axis)

In [ ]:
(Sa(image),
 Sa(image,axis = (0,1)),
 Sa(sections,sections=True)[:3],
 Sa(sections,axis=(1,2))[:3])

(0.00047688714130073284,
 0.00047688714130073284,
 array([0.00028241, 0.00042414, 0.00020014]),
 array([0.00028241, 0.00042414, 0.00020014]))

In [ ]:
#| export
def Sms(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Sms of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
       ):
    '''
    Calculates the root mean square difference from the mean plane. Equivalent to Rms(array, axis = None)
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims = True)

    return np.sqrt(np.mean(np.square(im), axis = axis))

In [ ]:
(Sms(image),Sms(sections,sections=True)[:5])

(0.0006332906519311293,
 array([0.00032491, 0.00049684, 0.0002654 , 0.00028618, 0.0004129 ]))

In [ ]:
#| export
def Ssk(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Ssk of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
       ):
    '''
    Calculates the Skew of the section. Equivalent to Rsk(im, axis = None) for an (m,n) array
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims = True)
     
    return skew(a = im, axis=axis, **kwargs)
        
        

In [ ]:
(Ssk(image),Ssk(sections, sections = True)[:5])

(0.09500122790758757,
 array([-0.09524635,  0.28831296,  0.70445168, -0.75446586, -0.02569195]))

In [ ]:
#| export
def Sku(im, #Numpy array or arraylike. typically (m,n) for 1 array or (k,m,n) for k (m,n) stacked arrays
        norm = True,
        axis = None,
        sections = False, #If true, calculates the Sku of the stack of images, (i.e. sets axis = (1,2))
        **kwargs
       ):
    '''
    Calculates the Kurtosis of the section. Equivalent to Rku(im, axis = None) for an (m,n) array
    '''
    if sections:
        axis = (1,2)
    if norm:
        im = im - np.mean(im, axis = axis, keepdims = True)
     
    return kurtosis(a = im, axis=axis, **kwargs)

In [ ]:
(Sku(image),Sku(sections,sections=True)[:5])

(1.705202900719974,
 array([-1.06809856, -0.88850324,  1.07656068, -0.61641668, -0.91538318]))

In [ ]:
array_1 = np.ones((4,4))
array_2 = np.ones((4,4)) * 2
array_3 = np.ones((4,4)) * 3
stacked = np.array([array_1, array_2, array_3,array_2])
stacked

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [ ]:
norm_stacked = stacked - np.mean(stacked,axis = (1,2), keepdims=True)
norm_stacked

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [ ]:
np.mean(stacked, axis=(1,2))

array([1., 2., 3., 2.])

In [ ]:
#| hide
from nbdev import nbdev_export
nbdev_export()